# Site settings
title: Junteng Liu
email: "jliugi@connect.ust.hk"
description: "PhD Candidate at HKUST NLP Group - Research on NLP and Machine Learning"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://hxt725543-creator.github.io/LJT-Homepage" # the base hostname & protocol for your site
author:
  name: Junteng Liu
  email: "jliugi@connect.ust.hk"
  github: Vicent0205
  twitter: junteng88716710
  scholar: "https://scholar.google.com/citations?hl=en&user=tbK9jl4AAAAJ&view_op=list_works&sortby=pubdate"

# Social profiles
github_username: Vicent0205
twitter_username: junteng88716710
google_scholar_url: "https://scholar.google.com/citations?hl=en&user=tbK9jl4AAAAJ&view_op=list_works&sortby=pubdate"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Pagination
paginate: 10
paginate_path: /page:num.html

# Navigation
include:
  - _pages

# Exclude from processing.
exclude:
  - .jekyll-cache
  - gemfiles
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
